# Generated by Django 5.2.13 on 2026-04-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_genre_options_alter_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
    ]
